version: '3.9'
services:
  api:
    build: .
    container_name: fb-image-service
    environment:
      - PORT=3000
      - API_BASE_URL=http://localhost:3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fb_images?schema=public
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - MINIO_BUCKET=images
      - FUSION_BRAIN_API_KEY=${FUSION_BRAIN_API_KEY}
      - FUSION_BRAIN_API_SECRET=${FUSION_BRAIN_API_SECRET}
      - FUSION_BRAIN_API_URL=https://api-key.fusionbrain.ai
    ports:
      - '3001:3000'
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fb_images
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data

volumes:
  pgdata: {}
  minio: {}
